-- 31_fix_folder_context_chat.sql
-- Corrección del contexto de carpetas en el chat
-- 
-- PROBLEMA IDENTIFICADO:
-- Cuando se accedía al chat desde una carpeta específica (con folderId y folderName
-- en los parámetros de URL), el bot no podía acceder a los archivos de la carpeta
-- porque no se estaba preparando el contexto de archivos para el tipo "folder".
--
-- CAUSA RAÍZ:
-- En la función handleSendMessage, solo se manejaban los contextos de tipo:
-- - "agenda" 
-- - "subject"
-- - "program"
-- 
-- Pero faltaba el caso para "folder", por lo que cuando el chat era de tipo folder,
-- no se preparaba el contexto de archivos y el bot respondía que no podía acceder
-- a los archivos.
--
-- SOLUCIÓN IMPLEMENTADA:
-- Se agregó el caso faltante para currentChat.contextType === "folder" en la
-- función handleSendMessage, que utiliza la misma lógica que el contexto de
-- asignatura pero con filtrado por carpeta.
--
-- CAMBIOS REALIZADOS:
-- - Agregado manejo de contexto de carpeta en handleSendMessage
-- - Utiliza prepareSubjectContextText() que ya tiene lógica para filtrar por folder_id
-- - Agregado logging específico para debugging del contexto de carpeta
-- - Mantenida la funcionalidad existente para otros tipos de contexto
--
-- ARCHIVOS MODIFICADOS:
-- - src/pages/Chat.tsx: Agregado caso para contextType === "folder"
--
-- NOTA: No se requieren cambios en la base de datos para esta corrección.
-- Los cambios son únicamente en la lógica del frontend.

-- Verificar que la funcionalidad esté funcionando correctamente
SELECT 'Contexto de carpeta corregido en el chat' as status;
