-- 32_fix_folder_context_query.sql
-- Corrección adicional para el contexto de carpetas en el chat
-- 
-- PROBLEMA IDENTIFICADO:
-- Aunque se agregó el caso para contextType === "folder" en handleSendMessage,
-- la función prepareSubjectContextText tenía una validación que requería
-- effectiveSubjectId para continuar, lo que impedía que funcionara correctamente
-- para contextos de carpeta que solo tienen folderId.
--
-- CAUSA RAÍZ:
-- La condición `if (!effectiveSubjectId || !user) return { text: "", files: [] };`
-- en prepareSubjectContextText impedía que se procesara el contexto de carpetas
-- cuando no había un subjectId válido, solo un folderId.
--
-- SOLUCIÓN IMPLEMENTADA:
-- 1. Separada la lógica de validación para contextos de carpeta vs otros contextos
-- 2. Para contexto de carpeta: solo requiere folderId
-- 3. Para otros contextos: requiere subjectId
-- 4. Actualizada la query para manejar ambos casos correctamente
-- 5. Mejorados los mensajes de contexto para carpetas
--
-- CAMBIOS REALIZADOS:
-- - Modificada la validación en prepareSubjectContextText
-- - Agregada lógica específica para contextType === "folder"
-- - Actualizada la query para filtrar por folder_id cuando corresponde
-- - Mejorados los mensajes de contexto para carpetas
--
-- ARCHIVOS MODIFICADOS:
-- - src/pages/Chat.tsx: Corregida la lógica de validación y query en prepareSubjectContextText
--
-- NOTA: No se requieren cambios en la base de datos para esta corrección.
-- Los cambios son únicamente en la lógica del frontend.

-- Verificar que la funcionalidad esté funcionando correctamente
SELECT 'Query de contexto de carpeta corregida' as status;
